### PR TITLE
Build shared version of libbenchmark

### PR DESCRIPTION
**Pull request by saraedum**
or is there a good reason why there should not be a shared library?

### CODE REVIEW

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender.

**Comment by saraedum** [comment]
The azure Wnidows build fails but it works on AppVeyor. I don't think I touched that part other than rerendering.

**Comment by xhochy** [comment]
@conda-forge-admin please rerender

**Comment by xhochy** [comment]
Thanks @saraedum !

**Pull request merged**
